name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main  # 当代码被推送到 main 分支时触发

jobs:
  build-android:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 系统作为构建环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 步骤1: 拉取你的代码

      - name: Set up Python
        uses: actions/setup-python@v4 # 步骤2: 设置 Python 环境
        with:
          python-version: '3.9' # 使用 Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 安装 buildozer 和它依赖的 cython
          # 固定 Cython 版本以提高构建稳定性
          pip install buildozer "cython==0.29.34"
          
          # (可选) 安装其他系统级依赖
          # sudo apt-get update
          # sudo apt-get install -y ...

      - name: Run Buildozer
        run: |
          # 运行 buildozer 命令来构建 debug 版本的 APK
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4 # 步骤3: 上传构建好的 APK 文件
        with:
          name: app-debug-apk # 上传产物的名称
          path: bin/*.apk # 指定 APK 文件所在的路径
