name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        
        # 修复 libtinfo5 问题
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
        sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
        
        # 安装完整版本的 autoconf 和 libtool
        wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
        tar xvf autoconf-2.69.tar.gz
        cd autoconf-2.69
        ./configure && make && sudo make install
        cd ..
        rm -rf autoconf-2.69*
        
        wget http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz
        tar xvf libtool-2.4.6.tar.gz
        cd libtool-2.4.6
        ./configure && make && sudo make install
        cd ..
        rm -rf libtool-2.4.6*

    - name: Install expect for automated inputs
      run: sudo apt-get install -y expect

    - name: Build APK with automated inputs
      run: |
        # 创建必要的 Android 目录结构
        mkdir -p "$HOME/.android"
        touch "$HOME/.android/repositories.cfg"
        
        # 使用 expect 自动应答许可协议
        expect -c '
          set timeout 180
          spawn buildozer android debug
          expect {
            "Do you accept the license*" { 
              send "y\r"
              exp_continue 
            }
            eof
          }
        '

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: meter-replacement-app
        path: bin/*.apk
