name: Build Android APK with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: crazymax/ndk:r21d  # 包含 NDK 21d 的稳定 Docker 镜像
      options: --privileged  # 需要特权模式以访问设备

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        # 安装必要的依赖
        apt-get update
        apt-get install -y python3-pip python3-dev python3-setuptools \
                          git zip unzip \
                          libncurses5 libncursesw5 libtinfo5 \
                          zlib1g-dev libssl-dev libffi-dev \
                          autoconf automake libtool pkg-config
        
        # 安装 Buildozer
        pip3 install --upgrade pip
        pip3 install buildozer cython virtualenv
        
        # 设置 Android SDK 路径
        echo "export ANDROID_SDK_ROOT=/sdk" >> ~/.bashrc
        echo "export ANDROID_NDK_ROOT=/opt/android-ndk" >> ~/.bashrc
        source ~/.bashrc
        
        # 创建并接受 Android SDK 许可
        mkdir -p /root/.android
        touch /root/.android/repositories.cfg
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > /root/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > /root/.android/licenses/android-sdk-arm-dbt-license

    - name: Build APK
      run: |
        # 设置环境变量自动接受许可
        export ANDROID_LICENSES_ACCEPT=yes
        
        # 初始化 Buildozer
        buildozer init -v
        
        # 修改 buildozer.spec 文件 (如果需要)
        sed -i "s|android.accept_sdk_license = False|android.accept_sdk_license = True|g" buildozer.spec
        sed -i "s|#android.ndk_path = |android.ndk_path = /opt/android-ndk|g" buildozer.spec
        sed -i "s|#android.sdk_path = |android.sdk_path = /sdk|g" buildozer.spec
        
        # 执行构建
        buildozer -v android release
        
        # 重命名 APK 文件
        cd bin
        for apk in *.apk; do
          mv "$apk" "meter-entry-${GITHUB_SHA:0:7}.apk"
        done

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: meter-entry-apk
        path: bin/*.apk
