name: Build APK

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main          # 推送到 main 分支时自动触发

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 缓存 Buildozer 依赖和 Android SDK/NDK
      - name: Cache .buildozer
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools \
                              git zip unzip openjdk-17-jdk \
                              libltdl-dev libffi-dev libssl-dev
          pip install --upgrade pip cython wheel buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
