# =======================================================================================
#
# GitHub Workflow for building Android APK with Buildozer
#
# Corrected version to resolve "repository not found" error.
# This workflow uses the official Kivy action to handle all dependencies,
# including Java, Android SDK/NDK, and license acceptance.
#
# =======================================================================================

name: Build Android APK with Buildozer

# Triggers the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-android:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build the APK using the official Kivy Buildozer Action
      # This action encapsulates all the complex setup steps.
      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1
        with:
          # The command that the action will execute
          command: buildozer -v android debug
          
          # (Optional) You can specify the path to your spec file if it's not in the root
          # spec_file: buildozer.spec

      # Step 3: Upload the generated APK as a workflow artifact
      # This makes the APK available for download from the Actions summary page.
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact in the summary
          name: app-debug-apk
          # The path to the file(s) to upload. The wildcard '*' captures the generated APK.
          path: bin/*.apk
