name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main  # 当代码被推送到 main 分支时触发

jobs:
  build-android:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为构建环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # 使用官方推荐的 Kivy Buildozer Action
        uses: kivy/buildozer-action@v1
        with:
          # 要执行的 buildozer 命令
          command: buildozer -v android debug
          
          # (可选) 指定 buildozer.spec 文件的位置
          # spec_file: buildozer.spec
          
          # (可选) 设置构建缓存，可以极大加快后续的构建速度
          # cache_name: buildozer-cache

      - name: Upload APK artifact
        # 上传构建产物 (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk # 上传产物的名称
          path: bin/*.apk # 指定 APK 文件所在的路径
