name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        # 修复 libtinfo5 问题
        wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.2-0ubuntu1_amd64.deb
        sudo dpkg -i libtinfo5_6.2-0ubuntu1_amd64.deb
        rm libtinfo5_6.2-0ubuntu1_amd64.deb
        
        # 安装完整版本的 autoconf 和 libtool
        wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
        tar xvf autoconf-2.69.tar.gz
        cd autoconf-2.69
        ./configure && make && sudo make install
        cd ..
        rm -rf autoconf-2.69*
        
        wget http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz
        tar xvf libtool-2.4.6.tar.gz
        cd libtool-2.4.6
        ./configure && make && sudo make install
        cd ..
        rm -rf libtool-2.4.6*
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv
        
    - name: Configure Buildozer
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget https://github.com/kivy/python-for-android/releases/download/2023.10.06/python-for-android-2023.10.06.tar.gz
        tar xvf python-for-android-2023.10.06.tar.gz
        mv python-for-android-2023.10.06 python-for-android
        rm python-for-android-2023.10.06.tar.gz
        
    - name: Build APK
      run: |
        # 清除之前的构建缓存
        buildozer android clean
        
        # 设置环境变量避免符号问题
        export LDFLAGS="-Wl,--no-as-needed"
        export LIBS="-ltinfo"
        
        # 使用更稳定的 NDK 版本
        buildozer -v android release \
          -- --ndk_version=21d \
          --sdk_version=24
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: meter-entry-app
        path: bin/*.apk
