name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        
        # 修复 libtinfo5 问题
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
        sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
        
        # 安装完整版本的 autoconf 和 libtool
        wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
        tar xvf autoconf-2.69.tar.gz
        cd autoconf-2.69
        ./configure && make && sudo make install
        cd ..
        rm -rf autoconf-2.69*
        
        wget http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz
        tar xvf libtool-2.4.6.tar.gz
        cd libtool-2.4.6
        ./configure && make && sudo make install
        cd ..
        rm -rf libtool-2.4.6*

    - name: Install expect for automated inputs
      run: sudo apt-get install -y expect

    - name: Build APK with automated inputs
      run: |        
        # 使用 expect 自动应答许可协议
        expect -c '
  # 超时：每轮等待最多 300 秒
  set timeout 300

  # 启动构建
  spawn buildozer android debug

  # 循环处理各种可能的许可提示
  expect {
    -re {(?i)do you accept.*license} {
      send "y\r"
      exp_continue
    }
    -re {(?i)accept\?\s*\[?y\/?n\]?\:?} {
      send "y\r"
      exp_continue
    }
    -re {(?i)\(y\/N\)|\[y\/N\]} {
      send "y\r"
      exp_continue
    }
    timeout {
      send_user "\n[expect] 等待输出超时（> $timeout 秒），构建可能挂起。\n"
      exit 1
    }
    eof {
      # 读取被 spawn 进程的退出状态并向外传播
      catch wait result
      # result: {pid 1234 spawn_id 5 status 0 matched} 或 {.... CHILDKILLED .... code 2}
      set code [lindex $result 3]
      if {$code eq ""} { set code 0 }
      exit $code
    }
  }
'

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: meter-replacement-app
        path: bin/*.apk
